version: '3'
services:
  nhk-stream-dl:
    build:
      context: .
    environment:
      - CONFIG_PATH=/app/config.json
    volumes:
      - ./config.json:/app/config.json
      - ./recordings:/app/recordings
      - ./logs/ffmpeg.log:/app/ffmpeg.log