name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check for changes in main.py
        id: check_changes
        run: |
          if git diff-tree --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^main.py$'; then
            echo "main.py has changed"
            echo "::set-output name=changed::true"
          else
            echo "main.py has not changed"
            echo "::set-output name=changed::false"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sonumucesh/nhk-record:latest
        if: steps.check_changes.outputs.changed == 'true'